//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKrReporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKrReporter.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (E001). Problem with open/create (to write) log file: 
        ///   {0}.
        /// </summary>
        internal static string E001_NoAccessToLogFile {
            get {
                return ResourceManager.GetString("E001_NoAccessToLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (E002). That application have to be run with arguments. 
        ///   More you can read at page:
        ///   https://github.com/kkrysztofczyk/KKrReporter/wiki.
        /// </summary>
        internal static string E002_NoArguments {
            get {
                return ResourceManager.GetString("E002_NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (E003). Problem with adding informations to log file: 
        ///   {0}.
        /// </summary>
        internal static string E003_NoAccessWriteLogFile {
            get {
                return ResourceManager.GetString("E003_NoAccessWriteLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (E004). Problem with adding informations and closing log file:
        ///   {0}.
        /// </summary>
        internal static string E004_NoAccessCloseLogFile {
            get {
                return ResourceManager.GetString("E004_NoAccessCloseLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file {0} is not valid, 
        ///KKrReporter is not able process request without proper configuration file.
        ///Error description: 
        ///{1}
        ///more about configuration file you can read at:
        ///https://github.com/kkrysztofczyk/KKrReporter/wiki/Config-File.
        /// </summary>
        internal static string E005_IncorrectConfFile {
            get {
                return ResourceManager.GetString("E005_IncorrectConfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplication will be closed automiatically after 25 seconds.
        /// </summary>
        internal static string INF01_AppClose {
            get {
                return ResourceManager.GetString("INF01_AppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKrReporter Start: {0}.
        /// </summary>
        internal static string INF02_AppStartLog {
            get {
                return ResourceManager.GetString("INF02_AppStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of no access to default log file (E001), application will try to save information to temporary log file:
        ///   {0}.
        /// </summary>
        internal static string INF02_TempLogFileInfo {
            get {
                return ResourceManager.GetString("INF02_TempLogFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKrReporter End: {0}.
        /// </summary>
        internal static string INF03_AppCloseLog {
            get {
                return ResourceManager.GetString("INF03_AppCloseLog", resourceCulture);
            }
        }
    }
}
